const ArchitecturalElements = [
  // Category 1
  {
    name: "Balusters",
    image: "/products/architectural-elements/balusters/0060.png",
    subCategories: [
      {
        name: "Balusters",
        image: "/products/architectural-elements/balusters/0043.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "#",
      },
      {
        name: "Balusters",
        image: "/products/architectural-elements/balusters/0044.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "#",
      },
      {
        name: "Balusters",
        image: "/products/architectural-elements/balusters/0045.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "#",
      },
      {
        name: "Balusters",
        image: "/products/architectural-elements/balusters/0046.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "#",
      },
      {
        name: "Balusters",
        image: "/products/architectural-elements/balusters/0047.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "#",
      },
      {
        name: "Balusters",
        image: "/products/architectural-elements/balusters/0048.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "#",
      },
      {
        name: "Balusters",
        image: "/products/architectural-elements/balusters/0049.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "#",
      },
      {
        name: "Balusters",
        image: "/products/architectural-elements/balusters/0050.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "#",
      },
      {
        name: "Balusters",
        image: "/products/architectural-elements/balusters/0051.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "#",
      },
      {
        name: "Balusters",
        image: "/products/architectural-elements/balusters/0052.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "#",
      },
      {
        name: "Balusters",
        image: "/products/architectural-elements/balusters/0053.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "#",
      },
      {
        name: "Balusters",
        image: "/products/architectural-elements/balusters/0054.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "#",
      },
      {
        name: "Balusters",
        image: "/products/architectural-elements/balusters/0055.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "#",
      },
      {
        name: "Balusters",
        image: "/products/architectural-elements/balusters/0056.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "#",
      },
      {
        name: "Balusters",
        image: "/products/architectural-elements/balusters/0057.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "#",
      },
      {
        name: "Balusters",
        image: "/products/architectural-elements/balusters/0058.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
      },
      {
        name: "Balusters",
        image: "/products/architectural-elements/balusters/0059.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "#",
      },
      {
        name: "Balusters",
        image: "/products/architectural-elements/balusters/0060.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "#",
      },
      {
        name: "Balusters",
        image: "/products/architectural-elements/balusters/0061.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "#",
      },
      {
        name: "Balusters",
        image: "/products/architectural-elements/balusters/0062.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "#",
      },
      {
        name: "Balusters",
        image: "/products/architectural-elements/balusters/0063.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "#",
      },
      {
        name: "Balusters",
        image: "/products/architectural-elements/balusters/0064.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "#",
      },
      {
        name: "Balusters",
        image: "/products/architectural-elements/balusters/0065.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "#",
      },
      {
        name: "Balusters",
        image: "/products/architectural-elements/balusters/0066.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "#",
      },
      {
        name: "Balusters",
        image: "/products/architectural-elements/balusters/0067.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "#",
      },
      {
        name: "Balusters",
        image: "/products/architectural-elements/balusters/0068.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "#",
      },
      {
        name: "Balusters",
        image: "/products/architectural-elements/balusters/0069.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "#",
      },
      {
        name: "Balusters",
        image: "/products/architectural-elements/balusters/0070.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "#",
      },
      {
        name: "Balusters",
        image: "/products/architectural-elements/balusters/0071.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "#",
      },
      {
        name: "Balusters",
        image: "/products/architectural-elements/balusters/0072.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "#",
      },
      {
        name: "Balusters",
        image: "/products/architectural-elements/balusters/0073.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "#",
      },
      {
        name: "Balusters",
        image: "/products/architectural-elements/balusters/0074.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "#",
      },
    ],
  },
  // Category 2
  {
    name: "Bollards",
    image: "/products/architectural-elements/bollards/0030.png",
    subCategories: [
      {
        name: "Bollards",
        image: "/products/architectural-elements/bollards/0026.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "#",
      },
      {
        name: "Bollards",
        image: "/products/architectural-elements/bollards/0027.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "#",
      },
      {
        name: "Bollards",
        image: "/products/architectural-elements/bollards/0028.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "#",
      },
      {
        name: "Bollards",
        image: "/products/architectural-elements/bollards/0029.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "#",
      },
      {
        name: "Bollards",
        image: "/products/architectural-elements/bollards/0030.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "#",
      },
      {
        name: "Bollards",
        image: "/products/architectural-elements/bollards/0031.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "#",
      },
      {
        name: "Bollards",
        image: "/products/architectural-elements/bollards/0032.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "#",
      },
      {
        name: "Bollards",
        image: "/products/architectural-elements/bollards/0033.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "#",
      },
      {
        name: "Bollards",
        image: "/products/architectural-elements/bollards/0034.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "#",
      },
      {
        name: "Bollards",
        image: "/products/architectural-elements/bollards/0035.png",
        downloadPdf: "#",
        download3d: "#",
      },
      {
        name: "Bollards",
        image: "/products/architectural-elements/bollards/0036.png",
        downloadPdf: "#",
        download3d: "#",
      },
      {
        name: "Bollards",
        image: "/products/architectural-elements/bollards/0037.png",
        downloadPdf: "#",
        download3d: "#",
      },
      {
        name: "Bollards",
        image: "/products/architectural-elements/bollards/0038.png",
        downloadPdf: "#",
        download3d: "#",
      },
      {
        name: "Bollards",
        image: "/products/architectural-elements/bollards/0039.png",
        downloadPdf: "#",
        download3d: "#",
      },
      {
        name: "Bollards",
        image: "/products/architectural-elements/bollards/0040.png",
        downloadPdf: "#",
        download3d: "#",
      },
      {
        name: "Bollards",
        image: "/products/architectural-elements/bollards/0041.png",
        downloadPdf: "#",
        download3d: "#",
      },
      {
        name: "Bollards",
        image: "/products/architectural-elements/bollards/0042.png",
        downloadPdf: "#",
        download3d: "#",
      },
    ],
  },
  // Category 3
  {
    name: "Columns",
    image: "/products/architectural-elements/columns/0006.png",
    subCategories: [
      {
        name: "Columns",
        image: "/products/architectural-elements/columns/0001.png",
        downloadPdf: "#",
        download3d: "#",
      },
      {
        name: "Columns",
        image: "/products/architectural-elements/columns/0002.png",
        downloadPdf: "#",
        download3d: "#",
      },
      {
        name: "Columns",
        image: "/products/architectural-elements/columns/0003.png",
        downloadPdf: "#",
        download3d: "#",
      },
      {
        name: "Columns",
        image: "/products/architectural-elements/columns/0006.png",
        downloadPdf: "#",
        download3d: "#",
      },
      {
        name: "Columns",
        image: "/products/architectural-elements/columns/0008.png",
        downloadPdf: "#",
        download3d: "#",
      },
      {
        name: "Columns",
        image: "/products/architectural-elements/columns/0011.png",
        downloadPdf: "#",
        download3d: "#",
      },
      {
        name: "Columns",
        image: "/products/architectural-elements/columns/0018.png",
        downloadPdf: "#",
        download3d: "#",
      },
      {
        name: "Columns",
        image: "/products/architectural-elements/columns/0024.png",
        downloadPdf: "#",
        download3d: "#",
      },
    ],
  },
  // Category 4
  {
    name: "Screens or Jali",
    image: "/products/architectural-elements/screens-or-jali/75 Dholpur.png",
    subCategories: [
      {
        name: "Screens or Jali",
        image: "/products/architectural-elements/screens-or-jali/1 Grey.png",
        downloadPdf: "#",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image: "/products/architectural-elements/screens-or-jali/2 Pink.png",
        downloadPdf: "#",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image: "/products/architectural-elements/screens-or-jali/3 Dholpur.png",
        downloadPdf: "#",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image: "/products/architectural-elements/screens-or-jali/4 White.png",
        downloadPdf: "#",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image: "/products/architectural-elements/screens-or-jali/5 Grey.png",
        downloadPdf: "#",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image: "/products/architectural-elements/screens-or-jali/6 Pink.png",
        downloadPdf: "#",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image: "/products/architectural-elements/screens-or-jali/7 Dholpur.png",
        downloadPdf: "#",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image: "/products/architectural-elements/screens-or-jali/8 White.png",
        downloadPdf: "#",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image: "/products/architectural-elements/screens-or-jali/9 Grey.png",
        downloadPdf: "#",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image: "/products/architectural-elements/screens-or-jali/10 Pink.png",
        downloadPdf: "#",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image:
          "/products/architectural-elements/screens-or-jali/11 Dholpur.png",
        downloadPdf: "#",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image: "/products/architectural-elements/screens-or-jali/12 White.png",
        downloadPdf: "#",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image: "/products/architectural-elements/screens-or-jali/13 Grey.png",
        downloadPdf: "#",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image: "/products/architectural-elements/screens-or-jali/14 Pink.png",
        downloadPdf: "#",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image:
          "/products/architectural-elements/screens-or-jali/15 Dholpur.png",
        downloadPdf: "#",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image: "/products/architectural-elements/screens-or-jali/16 White.png",
        downloadPdf: "#",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image: "/products/architectural-elements/screens-or-jali/17 Grey.png",
        downloadPdf: "#",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image: "/products/architectural-elements/screens-or-jali/18 Pink.png",
        downloadPdf: "#",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image:
          "/products/architectural-elements/screens-or-jali/19 Dholpur.png",
        downloadPdf: "#",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image: "/products/architectural-elements/screens-or-jali/20 White.png",
        downloadPdf: "#",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image: "/products/architectural-elements/screens-or-jali/21 Grey.png",
        downloadPdf: "#",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image: "/products/architectural-elements/screens-or-jali/22 Pink.png",
        downloadPdf: "#",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image:
          "/products/architectural-elements/screens-or-jali/23 Dholpur.png",
        downloadPdf: "#",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image: "/products/architectural-elements/screens-or-jali/24 White.png",
        downloadPdf: "#",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image: "/products/architectural-elements/screens-or-jali/25 Grey.png",
        downloadPdf: "#",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image: "/products/architectural-elements/screens-or-jali/26 Pink.png",
        downloadPdf: "#",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image:
          "/products/architectural-elements/screens-or-jali/27 Dholpur.png",
        downloadPdf: "#",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image: "/products/architectural-elements/screens-or-jali/28 White.png",
        downloadPdf: "#",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image: "/products/architectural-elements/screens-or-jali/29 Grey.png",
        downloadPdf: "#",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image: "/products/architectural-elements/screens-or-jali/30 Pink.png",
        downloadPdf: "#",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image:
          "/products/architectural-elements/screens-or-jali/31 Dholpur.png",
        downloadPdf: "#",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image: "/products/architectural-elements/screens-or-jali/32 White.png",
        downloadPdf: "#",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image: "/products/architectural-elements/screens-or-jali/33 Grey.png",
        downloadPdf: "#",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image: "/products/architectural-elements/screens-or-jali/34 Pink.png",
        downloadPdf: "#",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image:
          "/products/architectural-elements/screens-or-jali/35 Dholpur.png",
        downloadPdf: "#",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image: "/products/architectural-elements/screens-or-jali/36 White.png",
        downloadPdf: "#",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image: "/products/architectural-elements/screens-or-jali/37 Grey.png",
        downloadPdf: "#",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image: "/products/architectural-elements/screens-or-jali/38 Pink.png",
        downloadPdf: "#",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image:
          "/products/architectural-elements/screens-or-jali/39 Dholpur.png",
        downloadPdf: "#",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image: "/products/architectural-elements/screens-or-jali/40 White.png",
        downloadPdf: "#",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image: "/products/architectural-elements/screens-or-jali/41 Grey.png",
        downloadPdf: "#",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image: "/products/architectural-elements/screens-or-jali/42 Pink.png",
        downloadPdf: "#",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image:
          "/products/architectural-elements/screens-or-jali/43 Dholpur.png",
        downloadPdf: "#",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image: "/products/architectural-elements/screens-or-jali/44 White.png",
        downloadPdf: "#",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image: "/products/architectural-elements/screens-or-jali/45 Grey.png",
        downloadPdf: "#",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image: "/products/architectural-elements/screens-or-jali/46 Pink.png",
        downloadPdf: "#",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image:
          "/products/architectural-elements/screens-or-jali/47 Dholpur.png",
        downloadPdf: "#",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image: "/products/architectural-elements/screens-or-jali/48 White.png",
        downloadPdf: "#",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image: "/products/architectural-elements/screens-or-jali/50 Pink.png",
        downloadPdf: "#",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image: "/products/architectural-elements/screens-or-jali/52 White.png",
        downloadPdf: "#",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image: "/products/architectural-elements/screens-or-jali/53 Grey.png",
        downloadPdf: "#",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image: "/products/architectural-elements/screens-or-jali/54 Pink.png",
        downloadPdf: "#",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image:
          "/products/architectural-elements/screens-or-jali/55 Dholpur.png",
        downloadPdf: "#",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image: "/products/architectural-elements/screens-or-jali/57 Grey.png",
        downloadPdf: "#",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image: "/products/architectural-elements/screens-or-jali/58 Pink.png",
        downloadPdf: "#",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image:
          "/products/architectural-elements/screens-or-jali/59 Dholpur.png",
        downloadPdf: "#",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image: "/products/architectural-elements/screens-or-jali/60 White.png",
        downloadPdf: "#",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image: "/products/architectural-elements/screens-or-jali/61 Grey.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image: "/products/architectural-elements/screens-or-jali/62 Pink.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image:
          "/products/architectural-elements/screens-or-jali/63 Dholpur.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image: "/products/architectural-elements/screens-or-jali/64 White.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image: "/products/architectural-elements/screens-or-jali/65 Grey.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image: "/products/architectural-elements/screens-or-jali/66 Pink.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image:
          "/products/architectural-elements/screens-or-jali/67 Dholpur.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image: "/products/architectural-elements/screens-or-jali/68 White.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image: "/products/architectural-elements/screens-or-jali/69 Grey.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image: "/products/architectural-elements/screens-or-jali/70 Pink.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image:
          "/products/architectural-elements/screens-or-jali/71 Dholpur.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image: "/products/architectural-elements/screens-or-jali/72 White.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image: "/products/architectural-elements/screens-or-jali/73 Grey.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image: "/products/architectural-elements/screens-or-jali/74 Pink.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image:
          "/products/architectural-elements/screens-or-jali/75 Dholpur.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image: "/products/architectural-elements/screens-or-jali/76 White.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image: "/products/architectural-elements/screens-or-jali/77 Grey.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image: "/products/architectural-elements/screens-or-jali/78 Pink.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image:
          "/products/architectural-elements/screens-or-jali/79 Dholpur.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image: "/products/architectural-elements/screens-or-jali/80 White.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image: "/products/architectural-elements/screens-or-jali/81 Grey.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image: "/products/architectural-elements/screens-or-jali/82 Pink.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image:
          "/products/architectural-elements/screens-or-jali/83 Dholpur.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image: "/products/architectural-elements/screens-or-jali/84 White.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image: "/products/architectural-elements/screens-or-jali/85 Grey.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image: "/products/architectural-elements/screens-or-jali/86 Pink.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image:
          "/products/architectural-elements/screens-or-jali/87 Dholpur.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image: "/products/architectural-elements/screens-or-jali/88 White.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image: "/products/architectural-elements/screens-or-jali/89 Grey.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image: "/products/architectural-elements/screens-or-jali/90 Pink.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image:
          "/products/architectural-elements/screens-or-jali/91 Dholpur.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image: "/products/architectural-elements/screens-or-jali/92 White.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image: "/products/architectural-elements/screens-or-jali/93 Grey.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image: "/products/architectural-elements/screens-or-jali/94 Pink.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image:
          "/products/architectural-elements/screens-or-jali/95 Dholpur.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image: "/products/architectural-elements/screens-or-jali/96 White.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image: "/products/architectural-elements/screens-or-jali/97 Grey.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image: "/products/architectural-elements/screens-or-jali/98 Pink.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image:
          "/products/architectural-elements/screens-or-jali/99 Dholpur.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image: "/products/architectural-elements/screens-or-jali/100 White.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "#",
      },
      {
        name: "Screens or Jali",
        image: "/products/architectural-elements/screens-or-jali/101 Grey.png",
        downloadPdf: "https://drive.google.com/file/d/1jUUN1mzI0Cg8B0x58j_MvWuKkgqRKCFZ/view?usp=sharing",
        download3d: "#",
      },
    ],
  },
];

export default ArchitecturalElements;
