const WallTilePages = [
  // Category 1
  {
    proxy: "wall-tiles",
    slug: "dry-cladding-forms",
    name: "Dry Cladding Forms",
    image: "/products/wall-tiles/dry-cladding-forms/dry-cladding-forms.png",
    subcategories: [
      {
        slug: "absqua",
        name: "Absqua",
        image: "/products/wall-tiles/dry-cladding-forms/absqua/absqua.png",
        textures: [
          {
            name: "Smooth",
            image: "/products/textures/smooth.png",
          },
        ],
        colors: [
          "#70453C",
          "#553D3C",
          "#614541",
          "#AA9277",
          "#673830",
          "#F1F1F1",
          "#72595C",
          "#2F2F2F",
          "#8A3937",
          "#A47F33",
          "#86583E",
          "#9B793D",
        ],
        sizeDescription: {
          dimensions: "600x600x40",
          areaM: "0.36",
          areaF: "3.87",
        },
        swatches: [
          "/products/wall-tiles/dry-cladding-forms/absqua/swatches/swatch-1.png",
          "/products/wall-tiles/dry-cladding-forms/absqua/swatches/swatch-2.png",
          "/products/wall-tiles/dry-cladding-forms/absqua/swatches/swatch-3.png",
        ],
        renders: [
          "/products/wall-tiles/dry-cladding-forms/absqua/renders/render-1.jpg",
          "/products/wall-tiles/dry-cladding-forms/absqua/renders/render-2.jpg",
          "/products/wall-tiles/dry-cladding-forms/absqua/renders/render-3.jpg",
          "/products/wall-tiles/dry-cladding-forms/absqua/renders/render-4.jpg",
        ],
        downloadPdf:
          "https://drive.google.com/file/d/1Z8B2vh3Ojf0Dvsz7prfFfZP5t7LC8cdo/view?usp=sharing",
        download3d: "#",
      },
      {
        slug: "abstre",
        name: "Abstre",
        image: "/products/wall-tiles/dry-cladding-forms/abstre/abstre.png",
        textures: [
          {
            name: "Smooth",
            image: "/products/textures/smooth.png",
          },
        ],
        colors: [
          "#70453C",
          "#553D3C",
          "#614541",
          "#AA9277",
          "#673830",
          "#F1F1F1",
          "#72595C",
          "#2F2F2F",
          "#8A3937",
          "#967732",
          "#676767",
          "#9B793D",
        ],
        sizeDescription: {
          dimensions: "600x600x40",
          areaM: "0.24",
          areaF: "2.58",
        },
        swatches: [
          "/products/wall-tiles/dry-cladding-forms/abstre/swatches/swatch-1.png",
          "/products/wall-tiles/dry-cladding-forms/abstre/swatches/swatch-2.png",
          "/products/wall-tiles/dry-cladding-forms/abstre/swatches/swatch-3.png",
        ],
        renders: [
          "/products/wall-tiles/dry-cladding-forms/abstre/renders/render-1.jpg",
          "/products/wall-tiles/dry-cladding-forms/abstre/renders/render-2.jpg",
          "/products/wall-tiles/dry-cladding-forms/abstre/renders/render-3.jpg",
          "/products/wall-tiles/dry-cladding-forms/abstre/renders/render-4.jpg",
        ],
        downloadPdf:
          "https://drive.google.com/file/d/1Z8B2vh3Ojf0Dvsz7prfFfZP5t7LC8cdo/view?usp=sharing",
        download3d: "#",
      },
      {
        slug: "altrec",
        name: "Altrec",
        image: "/products/wall-tiles/dry-cladding-forms/altrec/altrec.png",
        textures: [
          {
            name: "Smooth",
            image: "/products/textures/smooth.png",
          },
        ],
        colors: [
          "#70453C",
          "#553D3C",
          "#614541",
          "#735557",
          "#673830",
          "#72595C",
          "#2F2F2F",
          "#8A3937",
          "#967732",
          "#A47F33",
          "#9B793D",
          "#86583E",
        ],
        sizeDescription: {
          dimensions: "600x600x40",
          areaM: "0.24",
          areaF: "2.58",
        },
        swatches: [
          "/products/wall-tiles/dry-cladding-forms/altrec/swatches/swatch-1.png",
          "/products/wall-tiles/dry-cladding-forms/altrec/swatches/swatch-2.png",
          "/products/wall-tiles/dry-cladding-forms/altrec/swatches/swatch-3.png",
          "/products/wall-tiles/dry-cladding-forms/altrec/swatches/swatch-4.png",
        ],
        renders: [
          "/products/wall-tiles/dry-cladding-forms/altrec/renders/render-1.jpg",
          "/products/wall-tiles/dry-cladding-forms/altrec/renders/render-2.jpg",
          "/products/wall-tiles/dry-cladding-forms/altrec/renders/render-3.jpg",
          "/products/wall-tiles/dry-cladding-forms/altrec/renders/render-4.jpg",
        ],
        downloadPdf:
          "https://drive.google.com/file/d/1Z8B2vh3Ojf0Dvsz7prfFfZP5t7LC8cdo/view?usp=sharing",
        download3d: "#",
      },
      {
        slug: "anglefish",
        name: "Anglefish",
        image:
          "/products/wall-tiles/dry-cladding-forms/anglefish/anglefish.png",
        textures: [
          {
            name: "Smooth",
            image: "/products/textures/smooth.png",
          },
        ],
        colors: [
          "#70453C",
          "#553D3C",
          "#614541",
          "#676767",
          "#AA9277",
          "#967732",
          "#72595C",
          "#96241A",
          "#8A3937",
          "#86583E",
          "#9B793D",
          "#A47F33",
        ],
        sizeDescription: {
          dimensions: "400x300x40",
          areaM: "0.12",
          areaF: "1.29",
        },
        swatches: [
          "/products/wall-tiles/dry-cladding-forms/anglefish/swatches/swatch-1.png",
          "/products/wall-tiles/dry-cladding-forms/anglefish/swatches/swatch-2.png",
          "/products/wall-tiles/dry-cladding-forms/anglefish/swatches/swatch-3.png",
          "/products/wall-tiles/dry-cladding-forms/anglefish/swatches/swatch-4.png",
        ],
        renders: [
          "/products/wall-tiles/dry-cladding-forms/anglefish/renders/render-1.jpg",
          "/products/wall-tiles/dry-cladding-forms/anglefish/renders/render-2.jpg",
          "/products/wall-tiles/dry-cladding-forms/anglefish/renders/render-3.jpg",
          "/products/wall-tiles/dry-cladding-forms/anglefish/renders/render-4.jpg",
        ],
        downloadPdf:
          "https://drive.google.com/file/d/1Z8B2vh3Ojf0Dvsz7prfFfZP5t7LC8cdo/view?usp=sharing",
        download3d: "#",
      },
      {
        slug: "crosquare",
        name: "Crosquare",
        image:
          "/products/wall-tiles/dry-cladding-forms/crosquare/crosquare.png",
        textures: [
          {
            name: "Smooth",
            image: "/products/textures/smooth.png",
          },
        ],
        colors: [
          "#70453C",
          "#553D3C",
          "#614541",
          "#AA9277",
          "#72595C",
          "#673830",
          "#967732",
          "#96241A",
          "#8A3937",
          "#A47F33",
          "#9B793D",
          "#F1F1F1",
        ],
        sizeDescription: {
          dimensions: "600x600x40",
          areaM: "0.36",
          areaF: "3.87",
        },
        swatches: [
          "/products/wall-tiles/dry-cladding-forms/crosquare/swatches/swatch-1.png",
          "/products/wall-tiles/dry-cladding-forms/crosquare/swatches/swatch-2.png",
          "/products/wall-tiles/dry-cladding-forms/crosquare/swatches/swatch-3.png",
          "/products/wall-tiles/dry-cladding-forms/crosquare/swatches/swatch-4.png",
        ],
        renders: [
          "/products/wall-tiles/dry-cladding-forms/crosquare/renders/render-1.jpg",
          "/products/wall-tiles/dry-cladding-forms/crosquare/renders/render-2.jpg",
          "/products/wall-tiles/dry-cladding-forms/crosquare/renders/render-3.jpg",
          "/products/wall-tiles/dry-cladding-forms/crosquare/renders/render-4.jpg",
        ],
        downloadPdf:
          "https://drive.google.com/file/d/1Z8B2vh3Ojf0Dvsz7prfFfZP5t7LC8cdo/view?usp=sharing",
        download3d: "#",
      },
      {
        slug: "hexchain",
        name: "Hexchain",
        image: "/products/wall-tiles/dry-cladding-forms/hexchain/hexchain.png",
        textures: [
          {
            name: "Smooth",
            image: "/products/textures/smooth.png",
          },
        ],
        colors: [
          "#553D3C",
          "#614541",
          "#735557",
          "#676767",
          "#72595C",
          "#673830",
          "#967732",
          "#AA9277",
          "#9B793D",
          "#86583E",
          "#2F2F2F",
          "#F1F1F1",
        ],
        sizeDescription: {
          dimensions: "600x300x40",
          areaM: "0.18",
          areaF: "1.93",
        },
        swatches: [
          "/products/wall-tiles/dry-cladding-forms/hexchain/swatches/swatch-1.png",
          "/products/wall-tiles/dry-cladding-forms/hexchain/swatches/swatch-2.png",
          "/products/wall-tiles/dry-cladding-forms/hexchain/swatches/swatch-3.png",
          "/products/wall-tiles/dry-cladding-forms/hexchain/swatches/swatch-4.png",
        ],
        renders: [
          "/products/wall-tiles/dry-cladding-forms/hexchain/renders/render-1.jpg",
          "/products/wall-tiles/dry-cladding-forms/hexchain/renders/render-2.jpg",
          "/products/wall-tiles/dry-cladding-forms/hexchain/renders/render-3.jpg",
          "/products/wall-tiles/dry-cladding-forms/hexchain/renders/render-4.jpg",
        ],
        downloadPdf:
          "https://drive.google.com/file/d/1Z8B2vh3Ojf0Dvsz7prfFfZP5t7LC8cdo/view?usp=sharing",
        download3d: "#",
      },
      {
        slug: "hexstar",
        name: "Hexstar",
        image: "/products/wall-tiles/dry-cladding-forms/hexstar/hexstar.png",
        textures: [
          {
            name: "Smooth",
            image: "/products/textures/smooth.png",
          },
        ],
        colors: [
          "#70453C",
          "#553D3C",
          "#614541",
          "#735557",
          "#673830",
          "#F1F1F1",
          "#8A3937",
          "#676767",
          "#8A3937",
          "#AA9277",
          "#9B793D",
          "#86583E",
          "#967732",
        ],
        sizeDescription: {
          dimensions: "600x600x40",
          areaM: "0.36",
          areaF: "3.87",
        },
        swatches: [
          "/products/wall-tiles/dry-cladding-forms/hexstar/swatches/swatch-1.png",
          "/products/wall-tiles/dry-cladding-forms/hexstar/swatches/swatch-2.png",
          "/products/wall-tiles/dry-cladding-forms/hexstar/swatches/swatch-3.png",
          "/products/wall-tiles/dry-cladding-forms/hexstar/swatches/swatch-4.png",
        ],
        renders: [
          "/products/wall-tiles/dry-cladding-forms/hexstar/renders/render-1.jpg",
          "/products/wall-tiles/dry-cladding-forms/hexstar/renders/render-2.jpg",
          "/products/wall-tiles/dry-cladding-forms/hexstar/renders/render-3.jpg",
          "/products/wall-tiles/dry-cladding-forms/hexstar/renders/render-4.jpg",
        ],
        downloadPdf:
          "https://drive.google.com/file/d/1Z8B2vh3Ojf0Dvsz7prfFfZP5t7LC8cdo/view?usp=sharing",
        download3d: "#",
      },
      {
        slug: "mapell",
        name: "Mapell",
        image: "/products/wall-tiles/dry-cladding-forms/mapell/mapell.png",
        textures: [
          {
            name: "Smooth",
            image: "/products/textures/smooth.png",
          },
        ],
        colors: [
          "#70453C",
          "#553D3C",
          "#614541",
          "#735557",
          "#676767",
          "#72595C",
          "#8A3937",
          "#673830",
          "#86583E",
          "#9B793D",
          "#967732",
          "#A47F33",
        ],
        sizeDescription: {
          dimensions: "600x500x40",
          areaM: "0.3",
          areaF: "3.22",
        },
        swatches: [
          "/products/wall-tiles/dry-cladding-forms/mapell/swatches/swatch-1.png",
          "/products/wall-tiles/dry-cladding-forms/mapell/swatches/swatch-2.png",
          "/products/wall-tiles/dry-cladding-forms/mapell/swatches/swatch-3.png",
          "/products/wall-tiles/dry-cladding-forms/mapell/swatches/swatch-4.png",
        ],
        renders: [
          "/products/wall-tiles/dry-cladding-forms/mapell/renders/render-1.jpg",
          "/products/wall-tiles/dry-cladding-forms/mapell/renders/render-2.jpg",
          "/products/wall-tiles/dry-cladding-forms/mapell/renders/render-3.jpg",
          "/products/wall-tiles/dry-cladding-forms/mapell/renders/render-4.jpg",
        ],
        downloadPdf:
          "https://drive.google.com/file/d/1Z8B2vh3Ojf0Dvsz7prfFfZP5t7LC8cdo/view?usp=sharing",
        download3d: "#",
      },
      {
        slug: "peepal",
        name: "Peepal",
        image: "/products/wall-tiles/dry-cladding-forms/peepal/peepal.png",
        textures: [
          {
            name: "Smooth",
            image: "/products/textures/smooth.png",
          },
        ],
        colors: [
          "#70453C",
          "#553D3C",
          "#614541",
          "#735557",
          "#676767",
          "#72595C",
          "#8A3937",
          "#A47F33",
          "#AA9277",
          "#9B793D",
          "#967732",
          "#F1F1F1",
        ],
        sizeDescription: {
          dimensions: "600x500x40",
          areaM: "0.3",
          areaF: "3.22",
        },
        swatches: [
          "/products/wall-tiles/dry-cladding-forms/peepal/swatches/swatch-1.png",
          "/products/wall-tiles/dry-cladding-forms/peepal/swatches/swatch-2.png",
          "/products/wall-tiles/dry-cladding-forms/peepal/swatches/swatch-3.png",
          "/products/wall-tiles/dry-cladding-forms/peepal/swatches/swatch-4.png",
        ],
        renders: [
          "/products/wall-tiles/dry-cladding-forms/peepal/renders/render-1.jpg",
          "/products/wall-tiles/dry-cladding-forms/peepal/renders/render-2.jpg",
          "/products/wall-tiles/dry-cladding-forms/peepal/renders/render-3.jpg",
          "/products/wall-tiles/dry-cladding-forms/peepal/renders/render-4.jpg",
        ],
        downloadPdf:
          "https://drive.google.com/file/d/1Z8B2vh3Ojf0Dvsz7prfFfZP5t7LC8cdo/view?usp=sharing",
        download3d: "#",
      },
      {
        slug: "pinwheel",
        name: "Pinwheel",
        image: "/products/wall-tiles/dry-cladding-forms/pinwheel/pinwheel.png",
        textures: [
          {
            name: "Smooth",
            image: "/products/textures/smooth.png",
          },
        ],
        colors: [
          "#70453C",
          "#553D3C",
          "#614541",
          "#96241A",
          "#676767",
          "#72595C",
          "#673830",
          "#967732",
          "#AA9277",
          "#9B793D",
          "#86583E",
          "#2F2F2F",
        ],
        sizeDescription: {
          dimensions: "600x500x40",
          areaM: "0.3",
          areaF: "3.22",
        },
        swatches: [
          "/products/wall-tiles/dry-cladding-forms/pinwheel/swatches/swatch-1.png",
          "/products/wall-tiles/dry-cladding-forms/pinwheel/swatches/swatch-2.png",
          "/products/wall-tiles/dry-cladding-forms/pinwheel/swatches/swatch-3.png",
          "/products/wall-tiles/dry-cladding-forms/pinwheel/swatches/swatch-4.png",
        ],
        renders: [
          "/products/wall-tiles/dry-cladding-forms/pinwheel/renders/render-1.jpg",
          "/products/wall-tiles/dry-cladding-forms/pinwheel/renders/render-2.jpg",
          "/products/wall-tiles/dry-cladding-forms/pinwheel/renders/render-3.jpg",
          "/products/wall-tiles/dry-cladding-forms/pinwheel/renders/render-4.jpg",
        ],
        downloadPdf:
          "https://drive.google.com/file/d/1Z8B2vh3Ojf0Dvsz7prfFfZP5t7LC8cdo/view?usp=sharing",
        download3d: "#",
      },
      {
        slug: "trihex",
        name: "Trihex",
        image: "/products/wall-tiles/dry-cladding-forms/trihex/trihex.png",
        textures: [
          {
            name: "Smooth",
            image: "/products/textures/smooth.png",
          },
        ],
        colors: [
          "#70453C",
          "#553D3C",
          "#614541",
          "#735557",
          "#676767",
          "#72595C",
          "#96241A",
          "#8A3937",
          "#967732",
          "#A47F33",
          "#9B793D",
          "#86583E",
        ],
        sizeDescription: {
          dimensions: "600x400x40",
          areaM: "0.24",
          areaF: "2.58",
        },
        swatches: [
          "/products/wall-tiles/dry-cladding-forms/trihex/swatches/swatch-1.png",
          "/products/wall-tiles/dry-cladding-forms/trihex/swatches/swatch-2.png",
          "/products/wall-tiles/dry-cladding-forms/trihex/swatches/swatch-3.png",
        ],
        renders: [
          "/products/wall-tiles/dry-cladding-forms/trihex/renders/render-1.jpg",
          "/products/wall-tiles/dry-cladding-forms/trihex/renders/render-2.jpg",
          "/products/wall-tiles/dry-cladding-forms/trihex/renders/render-3.jpg",
          "/products/wall-tiles/dry-cladding-forms/trihex/renders/render-4.jpg",
        ],
        downloadPdf:
          "https://drive.google.com/file/d/1Z8B2vh3Ojf0Dvsz7prfFfZP5t7LC8cdo/view?usp=sharing",
        download3d: "#",
      },
    ],
  },
  // Category 2
  {
    proxy: "wall-tiles",
    slug: "dry-cladding-panels",
    name: "Dry Cladding Panels",
    image: "/products/wall-tiles/dry-cladding-panels/dry-cladding-panels.png",
    subcategories: [
      {
        slug: "autumn",
        name: "Autumn",
        image: "/products/wall-tiles/dry-cladding-panels/autumn/autumn.png",
        textures: [
          {
            name: "Smooth",
            image: "/products/textures/smooth.png",
          },
        ],
        colors: [
          "#70453C",
          "#553D3C",
          "#614541",
          "#735557",
          "#673830",
          "#967732",
          "#72595C",
          "#96241A",
          "#8A3937",
          "#A47F33",
          "#86583E",
          "#9B793D",
        ],
        sizeDescription: {
          dimensions: "1000x1000x50",
          areaM: "1.0",
          areaF: "10.76",
        },
        swatches: [
          "/products/wall-tiles/dry-cladding-panels/autumn/swatches/swatch-1.png",
          "/products/wall-tiles/dry-cladding-panels/autumn/swatches/swatch-2.png",
          "/products/wall-tiles/dry-cladding-panels/autumn/swatches/swatch-3.png",
          "/products/wall-tiles/dry-cladding-panels/autumn/swatches/swatch-4.png",
        ],
        renders: [
          "/products/wall-tiles/dry-cladding-panels/autumn/renders/render-1.jpg",
          "/products/wall-tiles/dry-cladding-panels/autumn/renders/render-2.jpg",
          "/products/wall-tiles/dry-cladding-panels/autumn/renders/render-3.jpg",
          "/products/wall-tiles/dry-cladding-panels/autumn/renders/render-4.jpg",
        ],
        downloadPdf:
          "https://drive.google.com/file/d/1Z8B2vh3Ojf0Dvsz7prfFfZP5t7LC8cdo/view?usp=sharing",
        download3d: "#",
      },
      {
        slug: "ledge-cut",
        name: "Ledge Cut",
        image:
          "/products/wall-tiles/dry-cladding-panels/ledge-cut/ledge-cut.png",
        textures: [
          {
            name: "Smooth",
            image: "/products/textures/smooth.png",
          },
        ],
        colors: [
          "#2F2F2F",
          "#553D3C",
          "#614541",
          "#735557",
          "#673830",
          "#967732",
          "#72595C",
          "#96241A",
          "#8A3937",
          "#A47F33",
          "#86583E",
          "#9B793D",
        ],
        sizeDescription: {
          dimensions: "1000x1000x50",
          areaM: "1.0",
          areaF: "10.76",
        },
        swatches: [
          "/products/wall-tiles/dry-cladding-panels/ledge-cut/swatches/swatch-1.png",
          "/products/wall-tiles/dry-cladding-panels/ledge-cut/swatches/swatch-2.png",
          "/products/wall-tiles/dry-cladding-panels/ledge-cut/swatches/swatch-3.png",
        ],
        renders: [
          "/products/wall-tiles/dry-cladding-panels/ledge-cut/renders/render-1.jpg",
          "/products/wall-tiles/dry-cladding-panels/ledge-cut/renders/render-2.jpg",
          "/products/wall-tiles/dry-cladding-panels/ledge-cut/renders/render-3.jpg",
        ],
        downloadPdf:
          "https://drive.google.com/file/d/1Z8B2vh3Ojf0Dvsz7prfFfZP5t7LC8cdo/view?usp=sharing",
        download3d: "#",
      },
      {
        slug: "ledge-stone",
        name: "Ledge Stone",
        image:
          "/products/wall-tiles/dry-cladding-panels/ledge-stone/ledge-stone.png",
        textures: [
          {
            name: "Smooth",
            image: "/products/textures/smooth.png",
          },
        ],
        colors: [
          "#70453C",
          "#553D3C",
          "#614541",
          "#735557",
          "#673830",
          "#967732",
          "#72595C",
          "#96241A",
          "#8A3937",
          "#A47F33",
          "#86583E",
          "#9B793D",
        ],
        sizeDescription: {
          dimensions: "1000x1000x50",
          areaM: "1.0",
          areaF: "10.76",
        },
        swatches: [
          "/products/wall-tiles/dry-cladding-panels/ledge-stone/swatches/swatch-1.png",
          "/products/wall-tiles/dry-cladding-panels/ledge-stone/swatches/swatch-2.png",
          "/products/wall-tiles/dry-cladding-panels/ledge-stone/swatches/swatch-3.png",
        ],
        renders: [
          "/products/wall-tiles/dry-cladding-panels/ledge-stone/renders/render-1.jpg",
          "/products/wall-tiles/dry-cladding-panels/ledge-stone/renders/render-2.jpg",
          "/products/wall-tiles/dry-cladding-panels/ledge-stone/renders/render-3.jpg",
        ],
        downloadPdf:
          "https://drive.google.com/file/d/1Z8B2vh3Ojf0Dvsz7prfFfZP5t7LC8cdo/view?usp=sharing",
        download3d: "#",
      },
      {
        slug: "p-tesella",
        name: "P Tesella",
        image:
          "/products/wall-tiles/dry-cladding-panels/p-tesella/p-tesella.png",
        textures: [
          {
            name: "Smooth",
            image: "/products/textures/smooth.png",
          },
        ],
        colors: [
          "#70453C",
          "#553D3C",
          "#614541",
          "#735557",
          "#673830",
          "#967732",
          "#72595C",
          "#96241A",
          "#8A3937",
          "#A47F33",
          "#86583E",
          "#9B793D",
        ],
        sizeDescription: {
          dimensions: "1000x1000x50",
          areaM: "1.0",
          areaF: "10.76",
        },
        swatches: [
          "/products/wall-tiles/dry-cladding-panels/p-tesella/swatches/swatch-1.png",
          "/products/wall-tiles/dry-cladding-panels/p-tesella/swatches/swatch-2.png",
          "/products/wall-tiles/dry-cladding-panels/p-tesella/swatches/swatch-3.png",
          "/products/wall-tiles/dry-cladding-panels/p-tesella/swatches/swatch-4.png",
        ],
        renders: [
          "/products/wall-tiles/dry-cladding-panels/p-tesella/renders/render-1.jpg",
          "/products/wall-tiles/dry-cladding-panels/p-tesella/renders/render-2.jpg",
          "/products/wall-tiles/dry-cladding-panels/p-tesella/renders/render-3.jpg",
          "/products/wall-tiles/dry-cladding-panels/p-tesella/renders/render-4.jpg",
        ],
        downloadPdf:
          "https://drive.google.com/file/d/1Z8B2vh3Ojf0Dvsz7prfFfZP5t7LC8cdo/view?usp=sharing",
        download3d: "#",
      },
      {
        slug: "scutes",
        name: "Scutes",
        image: "/products/wall-tiles/dry-cladding-panels/scutes/scutes.png",
        textures: [
          {
            name: "Smooth",
            image: "/products/textures/smooth.png",
          },
        ],
        colors: [
          "#70453C",
          "#553D3C",
          "#614541",
          "#735557",
          "#673830",
          "#967732",
          "#72595C",
          "#96241A",
          "#8A3937",
          "#A47F33",
          "#86583E",
          "#9B793D",
        ],
        sizeDescription: {
          dimensions: "1000x1000x50",
          areaM: "1.0",
          areaF: "10.76",
        },
        swatches: [
          "/products/wall-tiles/dry-cladding-panels/scutes/swatches/swatch-1.png",
          "/products/wall-tiles/dry-cladding-panels/scutes/swatches/swatch-2.png",
          "/products/wall-tiles/dry-cladding-panels/scutes/swatches/swatch-3.png",
          "/products/wall-tiles/dry-cladding-panels/scutes/swatches/swatch-4.png",
        ],
        renders: [
          "/products/wall-tiles/dry-cladding-panels/scutes/renders/render-1.jpg",
          "/products/wall-tiles/dry-cladding-panels/scutes/renders/render-2.jpg",
          "/products/wall-tiles/dry-cladding-panels/scutes/renders/render-3.jpg",
        ],
        downloadPdf:
          "https://drive.google.com/file/d/1Z8B2vh3Ojf0Dvsz7prfFfZP5t7LC8cdo/view?usp=sharing",
        download3d: "#",
      },
      {
        slug: "s-tesella",
        name: "S Tesella",
        image:
          "/products/wall-tiles/dry-cladding-panels/s-tesella/s-tesella.png",
        textures: [
          {
            name: "Smooth",
            image: "/products/textures/smooth.png",
          },
        ],
        colors: [
          "#70453C",
          "#553D3C",
          "#614541",
          "#735557",
          "#673830",
          "#967732",
          "#72595C",
          "#2F2F2F",
          "#8A3937",
          "#A47F33",
          "#86583E",
          "#9B793D",
        ],
        sizeDescription: {
          dimensions: "1000x1000x50",
          areaM: "1.0",
          areaF: "10.76",
        },
        swatches: [
          "/products/wall-tiles/dry-cladding-panels/s-tesella/swatches/swatch-1.png",
          "/products/wall-tiles/dry-cladding-panels/s-tesella/swatches/swatch-2.png",
          "/products/wall-tiles/dry-cladding-panels/s-tesella/swatches/swatch-3.png",
          "/products/wall-tiles/dry-cladding-panels/s-tesella/swatches/swatch-4.png",
        ],
        renders: [
          "/products/wall-tiles/dry-cladding-panels/s-tesella/renders/render-1.jpg",
          "/products/wall-tiles/dry-cladding-panels/s-tesella/renders/render-2.jpg",
          "/products/wall-tiles/dry-cladding-panels/s-tesella/renders/render-3.jpg",
          "/products/wall-tiles/dry-cladding-panels/s-tesella/renders/render-4.jpg",
        ],
        downloadPdf:
          "https://drive.google.com/file/d/1Z8B2vh3Ojf0Dvsz7prfFfZP5t7LC8cdo/view?usp=sharing",
        download3d: "#",
      },
      {
        slug: "tyde",
        name: "Tyde",
        image: "/products/wall-tiles/dry-cladding-panels/tyde/tyde.png",
        productImages: [
          "/products/wall-tiles/dry-cladding-panels/tyde/tyde.png",
          "/products/wall-tiles/dry-cladding-panels/tyde/tyde1.png",
          "/products/wall-tiles/dry-cladding-panels/tyde/tyde2.png",
        ],
        textures: [
          {
            name: "Smooth",
            image: "/products/textures/smooth.png",
          },
        ],
        colors: [
          "#70453C",
          "#553D3C",
          "#614541",
          "#735557",
          "#673830",
          "#967732",
          "#72595C",
          "#2F2F2F",
          "#8A3937",
          "#A47F33",
          "#86583E",
          "#9B793D",
        ],
        sizeDescription: {
          dimensions: "1000x1000x50",
          areaM: "1.0",
          areaF: "10.76",
        },
        swatches: [
          "/products/wall-tiles/dry-cladding-panels/tyde/swatches/swatch-1.png",
          "/products/wall-tiles/dry-cladding-panels/tyde/swatches/swatch-2.png",
          "/products/wall-tiles/dry-cladding-panels/tyde/swatches/swatch-3.png",
          "/products/wall-tiles/dry-cladding-panels/tyde/swatches/swatch-4.png",
        ],
        renders: [
          "/products/wall-tiles/dry-cladding-panels/tyde/renders/render-1.jpg",
          "/products/wall-tiles/dry-cladding-panels/tyde/renders/render-2.jpg",
          "/products/wall-tiles/dry-cladding-panels/tyde/renders/render-3.jpg",
          "/products/wall-tiles/dry-cladding-panels/tyde/renders/render-4.jpg",
        ],
        downloadPdf:
          "https://drive.google.com/file/d/1Z8B2vh3Ojf0Dvsz7prfFfZP5t7LC8cdo/view?usp=sharing",
        download3d: "#",
      },
      {
        slug: "v-flute",
        name: "V Flute",
        image: "/products/wall-tiles/dry-cladding-panels/v-flute/v-flute.png",
        textures: [
          {
            name: "Smooth",
            image: "/products/textures/smooth.png",
          },
        ],
        colors: [
          "#70453C",
          "#553D3C",
          "#614541",
          "#735557",
          "#673830",
          "#967732",
          "#72595C",
          "#96241A",
          "#8A3937",
          "#A47F33",
          "#86583E",
          "#9B793D",
        ],
        sizeDescription: {
          dimensions: "1000x1000x50",
          areaM: "1.0",
          areaF: "10.76",
        },
        swatches: [
          "/products/wall-tiles/dry-cladding-panels/v-flute/swatches/swatch-1.png",
          "/products/wall-tiles/dry-cladding-panels/v-flute/swatches/swatch-2.png",
          "/products/wall-tiles/dry-cladding-panels/v-flute/swatches/swatch-3.png",
          "/products/wall-tiles/dry-cladding-panels/v-flute/swatches/swatch-4.png",
          "/products/wall-tiles/dry-cladding-panels/v-flute/swatches/swatch-5.png",
        ],
        renders: [
          "/products/wall-tiles/dry-cladding-panels/v-flute/renders/render-1.jpg",
          "/products/wall-tiles/dry-cladding-panels/v-flute/renders/render-2.jpg",
          "/products/wall-tiles/dry-cladding-panels/v-flute/renders/render-3.jpg",
          "/products/wall-tiles/dry-cladding-panels/v-flute/renders/render-4.jpg",
        ],
        downloadPdf:
          "https://drive.google.com/file/d/1Z8B2vh3Ojf0Dvsz7prfFfZP5t7LC8cdo/view?usp=sharing",
        download3d: "#",
      },
    ],
  },
  // Category 3
  {
    proxy: "wall-tiles",
    slug: "wet-cladding-panel",
    name: "Wet Cladding Panel",
    image: "/products/wall-tiles/wet-cladding-panel/wet-cladding-panel.png",
    subcategories: [
      {
        slug: "arcade",
        name: "Arcade",
        image: "/products/wall-tiles/wet-cladding-panel/arcade/arcade.png",
        textures: [
          {
            name: "Coarse",
            image: "/products/textures/Coarse.png",
          },
        ],
        colors: [
          "#70453C",
          "#553D3C",
          "#614541",
          "#735557",
          "#673830",
          "#967732",
          "#AA9277",
          "#F1F1F1",
          "#A47F33",
          "#86583E",
          "#9B793D",
        ],
        sizeDescription: {
          dimensions: "300x900x15",
          areaM: "0.27",
          areaF: "2.91",
        },
        swatches: [
          "/products/wall-tiles/wet-cladding-panel/arcade/swatches/swatch-1.png",
          "/products/wall-tiles/wet-cladding-panel/arcade/swatches/swatch-2.png",
          "/products/wall-tiles/wet-cladding-panel/arcade/swatches/swatch-3.png",
        ],
        renders: [
          "/products/wall-tiles/wet-cladding-panel/arcade/renders/render-1.jpg",
          "/products/wall-tiles/wet-cladding-panel/arcade/renders/render-2.jpg",
          "/products/wall-tiles/wet-cladding-panel/arcade/renders/render-3.jpg",
        ],
        downloadPdf:
          "https://drive.google.com/file/d/1Z8B2vh3Ojf0Dvsz7prfFfZP5t7LC8cdo/view?usp=sharing",
        download3d: "#",
      },
      {
        slug: "ridges",
        name: "ridges",
        image: "/products/wall-tiles/wet-cladding-panel/ridges/ridges.png",
        textures: [
          {
            name: "Coarse",
            image: "/products/textures/Coarse.png",
          },
        ],
        colors: [
          "#70453C",
          "#553D3C",
          "#614541",
          "#2F2F2F",
          "#673830",
          "#967732",
          "#676767",
          "#F1F1F1",
          "#8A3937",
          "#A47F33",
          "#86583E",
          "#9B793D",
        ],
        sizeDescription: {
          dimensions: "600x900x22",
          areaM: "0.54",
          areaF: "5.81",
        },
        swatches: [
          "/products/wall-tiles/wet-cladding-panel/ridges/swatches/swatch-1.png",
          "/products/wall-tiles/wet-cladding-panel/ridges/swatches/swatch-2.png",
          "/products/wall-tiles/wet-cladding-panel/ridges/swatches/swatch-3.png",
          "/products/wall-tiles/wet-cladding-panel/ridges/swatches/swatch-4.png",
        ],
        renders: [
          "/products/wall-tiles/wet-cladding-panel/ridges/renders/render-1.jpg",
          "/products/wall-tiles/wet-cladding-panel/ridges/renders/render-2.jpg",
          "/products/wall-tiles/wet-cladding-panel/ridges/renders/render-3.jpg",
        ],
        downloadPdf:
          "https://drive.google.com/file/d/1Z8B2vh3Ojf0Dvsz7prfFfZP5t7LC8cdo/view?usp=sharing",
        download3d: "#",
      },
    ],
  },
  // Category 4
  {
    proxy: "wall-tiles",
    slug: "wet-cladding-tiles",
    name: "Wet Cladding Tiles",
    image: "/products/wall-tiles/wet-cladding-tiles/wet-cladding-tiles.png",
    subcategories: [
      {
        slug: "altpyra",
        name: "Altpyra",
        image: "/products/wall-tiles/wet-cladding-tiles/altpyra/altpyra.png",
        textures: [
          {
            name: "Smooth",
            image: "/products/textures/smooth.png",
          },
          {
            name: "Weathered",
            image: "/products/textures/weathered.png",
          },
        ],
        colors: [
          "#70453C",
          "#553D3C",
          "#614541",
          "#735557",
          "#967732",
          "#673830",
          "#72595C",
          "#96241A",
          "#8A3937",
          "#A47F33",
          "#86583E",
          "#9B793D",
        ],
        sizeDescription: {
          dimensions: "200x100x19",
          areaM: "0.2",
          areaF: "0.21",
        },
        swatches: [
          "/products/wall-tiles/wet-cladding-tiles/altpyra/swatches/swatch-1.png",
          "/products/wall-tiles/wet-cladding-tiles/altpyra/swatches/swatch-2.png",
          "/products/wall-tiles/wet-cladding-tiles/altpyra/swatches/swatch-3.png",
        ],
        renders: [
          "/products/wall-tiles/wet-cladding-tiles/altpyra/renders/render-1.jpg",
          "/products/wall-tiles/wet-cladding-tiles/altpyra/renders/render-2.jpg",
          "/products/wall-tiles/wet-cladding-tiles/altpyra/renders/render-3.jpg",
          "/products/wall-tiles/wet-cladding-tiles/altpyra/renders/render-4.jpg",
        ],
        downloadPdf:
          "https://drive.google.com/file/d/1Z8B2vh3Ojf0Dvsz7prfFfZP5t7LC8cdo/view?usp=sharing",
        download3d: "#",
      },
      {
        slug: "bamboo",
        name: "Bamboo",
        image: "/products/wall-tiles/wet-cladding-tiles/bamboo/bamboo.png",
        textures: [
          {
            name: "Smooth",
            image: "/products/textures/smooth.png",
          },
        ],
        colors: [
          "#70453C",
          "#553D3C",
          "#614541",
          "#735557",
          "#967732",
          "#F1F1F1",
          "#72595C",
          "#96241A",
          "#8A3937",
          "#A47F33",
          "#86583E",
          "#9B793D",
        ],
        sizeDescription: {
          dimensions: "256x125x15",
          areaM: "0.3",
          areaF: "0.34",
        },
        swatches: [
          "/products/wall-tiles/wet-cladding-tiles/bamboo/swatches/swatch-1.png",
          "/products/wall-tiles/wet-cladding-tiles/bamboo/swatches/swatch-2.png",
          "/products/wall-tiles/wet-cladding-tiles/bamboo/swatches/swatch-3.png",
          "/products/wall-tiles/wet-cladding-tiles/bamboo/swatches/swatch-4.png",
        ],
        renders: [
          "/products/wall-tiles/wet-cladding-tiles/bamboo/renders/render-1.jpg",
          "/products/wall-tiles/wet-cladding-tiles/bamboo/renders/render-2.jpg",
          "/products/wall-tiles/wet-cladding-tiles/bamboo/renders/render-3.jpg",
        ],
        downloadPdf:
          "https://drive.google.com/file/d/1Z8B2vh3Ojf0Dvsz7prfFfZP5t7LC8cdo/view?usp=sharing",
        download3d: "#",
      },
      {
        slug: "burrow",
        name: "Burrow",
        image: "/products/wall-tiles/wet-cladding-tiles/burrow/burrow.png",
        textures: [
          {
            name: "Almond Hem",
            image: "/products/textures/almond-hem.png",
          },
        ],
        colors: [
          "#70453C",
          "#553D3C",
          "#735557",
          "#8A3937",
          "#967732",
          "#673830",
          "#72595C",
          "#2F2F2F",
          "#676767",
          "#A47F33",
          "#86583E",
          "#9B793D",
        ],
        sizeDescription: {
          dimensions: "245x120x36",
          areaM: "0.29",
          areaF: "0.31",
        },
        swatches: [
          "/products/wall-tiles/wet-cladding-tiles/burrow/swatches/swatch-1.png",
          "/products/wall-tiles/wet-cladding-tiles/burrow/swatches/swatch-2.png",
          "/products/wall-tiles/wet-cladding-tiles/burrow/swatches/swatch-3.png",
          "/products/wall-tiles/wet-cladding-tiles/burrow/swatches/swatch-4.png",
        ],
        renders: [
          "/products/wall-tiles/wet-cladding-tiles/burrow/renders/render-1.jpg",
          "/products/wall-tiles/wet-cladding-tiles/burrow/renders/render-2.jpg",
          "/products/wall-tiles/wet-cladding-tiles/burrow/renders/render-3.jpg",
        ],
        downloadPdf:
          "https://drive.google.com/file/d/1Z8B2vh3Ojf0Dvsz7prfFfZP5t7LC8cdo/view?usp=sharing",
        download3d: "#",
      },
      {
        slug: "cliff-stone",
        name: "Cliff Stone",
        image:
          "/products/wall-tiles/wet-cladding-tiles/cliff-stone/cliff-stone.png",
        textures: [
          {
            name: "Stone",
            image: "/products/textures/stone.png",
          },
        ],
        colors: [
          "#70453C",
          "#553D3C",
          "#614541",
          "#735557",
          "#967732",
          "#673830",
          "#72595C",
          "#676767",
          "#8A3937",
          "#A47F33",
          "#86583E",
          "#9B793D",
        ],
        sizeDescription: {
          dimensions: "245x120x36",
          areaM: "0.23",
          areaF: "0.25",
        },
        swatches: [
          "/products/wall-tiles/wet-cladding-tiles/cliff-stone/swatches/swatch-1.png",
          "/products/wall-tiles/wet-cladding-tiles/cliff-stone/swatches/swatch-2.png",
          "/products/wall-tiles/wet-cladding-tiles/cliff-stone/swatches/swatch-3.png",
          "/products/wall-tiles/wet-cladding-tiles/cliff-stone/swatches/swatch-4.png",
        ],
        renders: [
          "/products/wall-tiles/wet-cladding-tiles/cliff-stone/renders/render-1.jpg",
          "/products/wall-tiles/wet-cladding-tiles/cliff-stone/renders/render-2.jpg",
          "/products/wall-tiles/wet-cladding-tiles/cliff-stone/renders/render-3.jpg",
        ],
        downloadPdf:
          "https://drive.google.com/file/d/1Z8B2vh3Ojf0Dvsz7prfFfZP5t7LC8cdo/view?usp=sharing",
        download3d: "#",
      },
      {
        slug: "coarse-stone",
        name: "Coarse Stone",
        image:
          "/products/wall-tiles/wet-cladding-tiles/coarse-stone/coarse-stone.png",
        textures: [
          {
            name: "Stone",
            image: "/products/textures/stone.png",
          },
        ],
        colors: [
          "#70453C",
          "#553D3C",
          "#614541",
          "#F1F1F1",
          "#967732",
          "#673830",
          "#72595C",
          "#2F2F2F",
          "#676767",
          "#A47F33",
          "#86583E",
          "#9B793D",
        ],
        sizeDescription: {
          dimensions: "180x90x11",
          areaM: "0.016",
          areaF: "0.17",
        },
        swatches: [
          "/products/wall-tiles/wet-cladding-tiles/coarse-stone/swatches/swatch-1.png",
          "/products/wall-tiles/wet-cladding-tiles/coarse-stone/swatches/swatch-2.png",
          "/products/wall-tiles/wet-cladding-tiles/coarse-stone/swatches/swatch-3.png",
          "/products/wall-tiles/wet-cladding-tiles/coarse-stone/swatches/swatch-4.png",
        ],
        renders: [
          "/products/wall-tiles/wet-cladding-tiles/coarse-stone/renders/render-1.jpg",
          "/products/wall-tiles/wet-cladding-tiles/coarse-stone/renders/render-2.jpg",
          "/products/wall-tiles/wet-cladding-tiles/coarse-stone/renders/render-3.jpg",
        ],
        downloadPdf: "#",
        download3d: "#",
      },
      {
        slug: "country-stone",
        name: "Country Stone",
        image:
          "/products/wall-tiles/wet-cladding-tiles/country-stone/country-stone.png",
        textures: [
          {
            name: "Stone",
            image: "/products/textures/stone.png",
          },
        ],
        colors: [
          "#70453C",
          "#553D3C",
          "#614541",
          "#735557",
          "#967732",
          "#673830",
          "#AA9277",
          "#676767",
          "#2F2F2F",
          "#A47F33",
          "#86583E",
          "#9B793D",
        ],
        sizeDescription: {
          dimensions: "260x105x20",
          areaM: "0.027",
          areaF: "0.29",
        },
        swatches: [
          "/products/wall-tiles/wet-cladding-tiles/country-stone/swatches/swatch-1.png",
          "/products/wall-tiles/wet-cladding-tiles/country-stone/swatches/swatch-2.png",
          "/products/wall-tiles/wet-cladding-tiles/country-stone/swatches/swatch-3.png",
        ],
        renders: [
          "/products/wall-tiles/wet-cladding-tiles/country-stone/renders/render-1.jpg",
          "/products/wall-tiles/wet-cladding-tiles/country-stone/renders/render-2.jpg",
          "/products/wall-tiles/wet-cladding-tiles/country-stone/renders/render-3.jpg",
        ],
        downloadPdf: "#",
        download3d: "#",
      },
      {
        slug: "curve-weave",
        name: "Curve Weave",
        image:
          "/products/wall-tiles/wet-cladding-tiles/curve-weave/curve-weave.png",
        textures: [
          {
            name: "Almond Hem",
            image: "/products/textures/almond-hem.png",
          },
        ],
        colors: [
          "#70453C",
          "#553D3C",
          "#614541",
          "#2F2F2F",
          "#967732",
          "#F1F1F1",
          "#72595C",
          "#96241A",
          "#8A3937",
          "#A47F33",
          "#86583E",
          "#676767",
        ],
        sizeDescription: {
          dimensions: "244x50x19",
          areaM: "0.012",
          areaF: "0.13",
        },
        swatches: [
          "/products/wall-tiles/wet-cladding-tiles/curve-weave/swatches/swatch-1.png",
          "/products/wall-tiles/wet-cladding-tiles/curve-weave/swatches/swatch-2.png",
          "/products/wall-tiles/wet-cladding-tiles/curve-weave/swatches/swatch-3.png",
        ],
        renders: [
          "/products/wall-tiles/wet-cladding-tiles/curve-weave/renders/render-1.jpg",
          "/products/wall-tiles/wet-cladding-tiles/curve-weave/renders/render-2.jpg",
          "/products/wall-tiles/wet-cladding-tiles/curve-weave/renders/render-3.jpg",
          "/products/wall-tiles/wet-cladding-tiles/curve-weave/renders/render-4.jpg",
        ],
        downloadPdf: "#",
        download3d: "#",
      },
      {
        slug: "furrow-cut",
        name: "Furrow Cut",
        image:
          "/products/wall-tiles/wet-cladding-tiles/furrow-cut/furrow-cut.png",
        textures: [
          {
            name: "Stone",
            image: "/products/textures/stone.png",
          },
        ],
        colors: [
          "#70453C",
          "#553D3C",
          "#614541",
          "#F1F1F1",
          "#967732",
          "#673830",
          "#72595C",
          "#2F2F2F",
          "#8A3937",
          "#A47F33",
          "#86583E",
          "#9B793D",
        ],
        sizeDescription: {
          dimensions: "245x120x36",
          areaM: "0.029",
          areaF: "0.31",
        },
        swatches: [
          "/products/wall-tiles/wet-cladding-tiles/furrow-cut/swatches/swatch-1.png",
          "/products/wall-tiles/wet-cladding-tiles/furrow-cut/swatches/swatch-2.png",
          "/products/wall-tiles/wet-cladding-tiles/furrow-cut/swatches/swatch-3.png",
          "/products/wall-tiles/wet-cladding-tiles/furrow-cut/swatches/swatch-4.png",
        ],
        renders: [
          "/products/wall-tiles/wet-cladding-tiles/furrow-cut/renders/render-1.jpg",
          "/products/wall-tiles/wet-cladding-tiles/furrow-cut/renders/render-2.jpg",
          "/products/wall-tiles/wet-cladding-tiles/furrow-cut/renders/render-3.jpg",
          "/products/wall-tiles/wet-cladding-tiles/furrow-cut/renders/render-4.jpg",
        ],
        downloadPdf: "#",
        download3d: "#",
      },
      {
        slug: "grit-wave",
        name: "Grit Wave",
        image:
          "/products/wall-tiles/wet-cladding-tiles/grit-wave/grit-wave.png",
        textures: [
          {
            name: "Weathered",
            image: "/products/textures/weathered.png",
          },
        ],
        colors: [
          "#70453C",
          "#553D3C",
          "#614541",
          "#735557",
          "#967732",
          "#673830",
          "#72595C",
          "#96241A",
          "#8A3937",
          "#A47F33",
          "#86583E",
          "#9B793D",
        ],
        sizeDescription: {
          dimensions: "286x41x22",
          areaM: "0.011",
          areaF: "0.12",
        },
        swatches: [
          "/products/wall-tiles/wet-cladding-tiles/grit-wave/swatches/swatch-1.png",
          "/products/wall-tiles/wet-cladding-tiles/grit-wave/swatches/swatch-2.png",
          "/products/wall-tiles/wet-cladding-tiles/grit-wave/swatches/swatch-3.png",
        ],
        renders: [
          "/products/wall-tiles/wet-cladding-tiles/grit-wave/renders/render-1.jpg",
          "/products/wall-tiles/wet-cladding-tiles/grit-wave/renders/render-2.jpg",
          "/products/wall-tiles/wet-cladding-tiles/grit-wave/renders/render-3.jpg",
        ],
        downloadPdf:
          "https://drive.google.com/file/d/1Z8B2vh3Ojf0Dvsz7prfFfZP5t7LC8cdo/view?usp=sharing",
        download3d: "#",
      },
      {
        slug: "hembrick",
        name: "Hembrick",
        image: "/products/wall-tiles/wet-cladding-tiles/hembrick/hembrick.png",
        textures: [
          {
            name: "Vein",
            image: "/products/textures/vein.png",
          },
        ],
        colors: [
          "#70453C",
          "#553D3C",
          "#614541",
          "#735557",
          "#967732",
          "#673830",
          "#72595C",
          "#2F2F2F",
          "#8A3937",
          "#A47F33",
          "#86583E",
          "#676767",
        ],
        sizeDescription: {
          dimensions: "230x78x15",
          areaM: "0.017",
          areaF: "0.19",
        },
        swatches: [
          "/products/wall-tiles/wet-cladding-tiles/hembrick/swatches/swatch-1.png",
          "/products/wall-tiles/wet-cladding-tiles/hembrick/swatches/swatch-2.png",
          "/products/wall-tiles/wet-cladding-tiles/hembrick/swatches/swatch-3.png",
        ],
        renders: [
          "/products/wall-tiles/wet-cladding-tiles/hembrick/renders/render-1.jpg",
          "/products/wall-tiles/wet-cladding-tiles/hembrick/renders/render-2.jpg",
          "/products/wall-tiles/wet-cladding-tiles/hembrick/renders/render-3.jpg",
          "/products/wall-tiles/wet-cladding-tiles/hembrick/renders/render-4.jpg",
        ],
        downloadPdf:
          "https://drive.google.com/file/d/1Z8B2vh3Ojf0Dvsz7prfFfZP5t7LC8cdo/view?usp=sharing",
        download3d: "#",
      },
      {
        slug: "sierra",
        name: "Sierra",
        image: "/products/wall-tiles/wet-cladding-tiles/sierra/sierra.png",
        textures: [
          {
            name: "Stone",
            image: "/products/textures/stone.png",
          },
        ],
        colors: [
          "#70453C",
          "#553D3C",
          "#614541",
          "#2F2F2F",
          "#967732",
          "#673830",
          "#72595C",
          "#96241A",
          "#676767",
          "#A47F33",
          "#86583E",
          "#9B793D",
        ],
        sizeDescription: {
          dimensions: "262x126x28",
          areaM: "0.033",
          areaF: "0.35",
        },
        swatches: [
          "/products/wall-tiles/wet-cladding-tiles/sierra/swatches/swatch-1.png",
          "/products/wall-tiles/wet-cladding-tiles/sierra/swatches/swatch-2.png",
          "/products/wall-tiles/wet-cladding-tiles/sierra/swatches/swatch-3.png",
          "/products/wall-tiles/wet-cladding-tiles/sierra/swatches/swatch-4.png",
        ],
        renders: [
          "/products/wall-tiles/wet-cladding-tiles/sierra/renders/render-1.jpg",
          "/products/wall-tiles/wet-cladding-tiles/sierra/renders/render-2.jpg",
          "/products/wall-tiles/wet-cladding-tiles/sierra/renders/render-3.jpg",
        ],
        downloadPdf:
          "https://drive.google.com/file/d/1Z8B2vh3Ojf0Dvsz7prfFfZP5t7LC8cdo/view?usp=sharing",
        download3d: "#",
      },
      {
        slug: "zenbrick",
        name: "Zenbrick",
        image: "/products/wall-tiles/wet-cladding-tiles/zenbrick/zenbrick.png",
        textures: [
          {
            name: "Smooth",
            image: "/products/textures/smooth.png",
          },
        ],
        colors: [
          "#70453C",
          "#553D3C",
          "#614541",
          "#735557",
          "#967732",
          "#673830",
          "#72595C",
          "#96241A",
          "#8A3937",
          "#A47F33",
          "#86583E",
          "#9B793D",
        ],
        sizeDescription: {
          dimensions: "230x78x15",
          areaM: "0.017",
          areaF: "0.019",
        },
        swatches: [
          "/products/wall-tiles/wet-cladding-tiles/zenbrick/swatches/swatch-1.png",
          "/products/wall-tiles/wet-cladding-tiles/zenbrick/swatches/swatch-2.png",
          "/products/wall-tiles/wet-cladding-tiles/zenbrick/swatches/swatch-3.png",
        ],
        renders: [
          "/products/wall-tiles/wet-cladding-tiles/zenbrick/renders/render-1.jpg",
          "/products/wall-tiles/wet-cladding-tiles/zenbrick/renders/render-2.jpg",
          "/products/wall-tiles/wet-cladding-tiles/zenbrick/renders/render-3.jpg",
          "/products/wall-tiles/wet-cladding-tiles/zenbrick/renders/render-4.jpg",
        ],
        downloadPdf:
          "https://drive.google.com/file/d/1Z8B2vh3Ojf0Dvsz7prfFfZP5t7LC8cdo/view?usp=sharing",
        download3d: "#",
      },
    ],
  },
];

export default WallTilePages;
