const WallTilePages = [
  {
    proxy: "wall-tiles",
    slug: "dry-cladding-forms",
    name: "Dry Cladding Forms",
    image: "/products/wall-tiles/dry-cladding-forms/dry-cladding-forms.png",
    subcategories: [
      {
        slug: "absqua",
        name: "Absqua",
        image: "/products/wall-tiles/dry-cladding-forms/absqua/absqua.png",
        textures: [
          {
            name: "Smooth",
            image: "/products/textures/smooth.png",
          },
        ],
        colors: [
          "brown 4610",
          "brown 4686",
          "brown 4660",
          "Dholpur",
          "Maroon",
          "White",
          "Pink",
          "Delhi Stone",
          "Red 4130",
          "yellow 4920",
          "yellow 4960",
          "yellow 4910",
        ],
        sizeDescription: {
          dimensions: "600x600x40",
          areaM: "0.36",
          areaF: "3.87",
        },
        swatches: [
          "/products/wall-tiles/dry-cladding-forms/absqua/swatches/swatch-1.jpg",
          "/products/wall-tiles/dry-cladding-forms/absqua/swatches/swatch-2.jpg",
          "/products/wall-tiles/dry-cladding-forms/absqua/swatches/swatch-3.jpg",
        ],
        renders: [
          "/products/wall-tiles/dry-cladding-forms/absqua/renders/render-1.jpg",
          "/products/wall-tiles/dry-cladding-forms/absqua/renders/render-2.jpg",
          "/products/wall-tiles/dry-cladding-forms/absqua/renders/render-3.jpg",
          "/products/wall-tiles/dry-cladding-forms/absqua/renders/render-4.jpg",
        ],
        downloadPdf: "#",
        download3d: "#",
      },
      {
        slug: "abstre",
        name: "Abstre",
        image: "/products/wall-tiles/dry-cladding-forms/abstre/abstre.png",
        textures: [
          {
            name: "Smooth",
            image: "/products/textures/smooth.png",
          },
        ],
        colors: [
          "brown 4610",
          "brown 4686",
          "brown 4660",
          "Dholpur",
          "Maroon",
          "White",
          "Pink",
          "Delhi Stone",
          "Red 4130",
          "yellow 4905",
          "grey",
          "yellow 4910",
        ],
        sizeDescription: {
          dimensions: "600x600x40",
          areaM: "0.24",
          areaF: "2.58",
        },
        swatches: [
          "/products/wall-tiles/dry-cladding-forms/abstre/swatches/swatch-1.jpg",
          "/products/wall-tiles/dry-cladding-forms/abstre/swatches/swatch-2.jpg",
          "/products/wall-tiles/dry-cladding-forms/abstre/swatches/swatch-3.jpg",
        ],
        renders: [
          "/products/wall-tiles/dry-cladding-forms/abstre/renders/render-1.jpg",
          "/products/wall-tiles/dry-cladding-forms/abstre/renders/render-2.jpg",
          "/products/wall-tiles/dry-cladding-forms/abstre/renders/render-3.jpg",
          "/products/wall-tiles/dry-cladding-forms/abstre/renders/render-4.jpg",
        ],
        downloadPdf: "#",
        download3d: "#",
      },
      {
        slug: "altrec",
        name: "Altrec",
        image: "/products/wall-tiles/dry-cladding-forms/altrec/altrec.png",
        textures: [
          {
            name: "Smooth",
            image: "/products/textures/smooth.png",
          },
        ],
        colors: [
          "brown 4610",
          "brown 4686",
          "brown 4660",
          "Red4180",
          "Maroon",
          "Pink",
          "Delhi Stone",
          "Red 4130",
          "yellow 4905",
          "yellow 4920",
          "yellow 4910",
          "yellow 4960",
        ],
        sizeDescription: {
          dimensions: "600x600x40",
          areaM: "0.24",
          areaF: "2.58",
        },
        swatches: [
          "/products/wall-tiles/dry-cladding-forms/altrec/swatches/swatch-1.jpg",
          "/products/wall-tiles/dry-cladding-forms/altrec/swatches/swatch-2.jpg",
          "/products/wall-tiles/dry-cladding-forms/altrec/swatches/swatch-3.jpg",
          "/products/wall-tiles/dry-cladding-forms/altrec/swatches/swatch-4.jpg",
        ],
        renders: [
          "/products/wall-tiles/dry-cladding-forms/altrec/renders/render-1.jpg",
          "/products/wall-tiles/dry-cladding-forms/altrec/renders/render-2.jpg",
          "/products/wall-tiles/dry-cladding-forms/altrec/renders/render-3.jpg",
          "/products/wall-tiles/dry-cladding-forms/altrec/renders/render-4.jpg",
        ],
        downloadPdf: "#",
        download3d: "#",
      },
      {
        slug: "anglefish",
        name: "Anglefish",
        image:
          "/products/wall-tiles/dry-cladding-forms/anglefish/anglefish.png",
        textures: [
          {
            name: "Smooth",
            image: "/products/textures/smooth.png",
          },
        ],
        colors: [
          "brown 4610",
          "brown 4686",
          "brown 4660",
          "Grey",
          "Dholpur",
          "Yellow 4905",
          "Pink",
          "Red 4100",
          "Red 4130",
          "Yellow 4960",
          "Yellow 4910",
          "Yellow 4920",
        ],
        sizeDescription: {
          dimensions: "400x300x40",
          areaM: "0.12",
          areaF: "1.29",
        },
        swatches: [
          "/products/wall-tiles/dry-cladding-forms/anglefish/swatches/swatch-1.jpg",
          "/products/wall-tiles/dry-cladding-forms/anglefish/swatches/swatch-2.jpg",
          "/products/wall-tiles/dry-cladding-forms/anglefish/swatches/swatch-3.jpg",
          "/products/wall-tiles/dry-cladding-forms/anglefish/swatches/swatch-4.jpg",
        ],
        renders: [
          "/products/wall-tiles/dry-cladding-forms/anglefish/renders/render-1.jpg",
          "/products/wall-tiles/dry-cladding-forms/anglefish/renders/render-2.jpg",
          "/products/wall-tiles/dry-cladding-forms/anglefish/renders/render-3.jpg",
          "/products/wall-tiles/dry-cladding-forms/anglefish/renders/render-4.jpg",
        ],
        downloadPdf: "#",
        download3d: "#",
      },
      {
        slug: "crosquare",
        name: "Crosquare",
        image:
          "/products/wall-tiles/dry-cladding-forms/crosquare/crosquare.png",
        textures: [
          {
            name: "Smooth",
            image: "/products/textures/smooth.png",
          },
        ],
        colors: [
          "brown 4610",
          "brown 4686",
          "brown 4660",
          "Dholpur",
          "Pink",
          "Maroon",
          "yellow 4905",
          "red 4100",
          "red 4130",
          "yellow 4920",
          "yellow 4910",
          "white",
        ],
        sizeDescription: {
          dimensions: "600x600x40",
          areaM: "0.36",
          areaF: "3.87",
        },
        swatches: [
          "/products/wall-tiles/dry-cladding-forms/crosquare/swatches/swatch-1.jpg",
          "/products/wall-tiles/dry-cladding-forms/crosquare/swatches/swatch-2.jpg",
          "/products/wall-tiles/dry-cladding-forms/crosquare/swatches/swatch-3.jpg",
          "/products/wall-tiles/dry-cladding-forms/crosquare/swatches/swatch-4.jpg",
        ],
        renders: [
          "/products/wall-tiles/dry-cladding-forms/crosquare/renders/render-1.jpg",
          "/products/wall-tiles/dry-cladding-forms/crosquare/renders/render-2.jpg",
          "/products/wall-tiles/dry-cladding-forms/crosquare/renders/render-3.jpg",
          "/products/wall-tiles/dry-cladding-forms/crosquare/renders/render-4.jpg",
        ],
        downloadPdf: "#",
        download3d: "#",
      },
      {
        slug: "hexchain",
        name: "Hexchain",
        image: "/products/wall-tiles/dry-cladding-forms/hexchain/hexchain.png",
        textures: [
          {
            name: "Smooth",
            image: "/products/textures/smooth.png",
          },
        ],
        colors: [
          "brown 4686",
          "brown 4660",
          "Red4180",
          "Grey",
          "Pink",
          "Maroon",
          "yellow 4905",
          "Dholpur",
          "yellow 4910",
          "yellow 4960",
          "Delhistone",
          "white",
        ],
        sizeDescription: {
          dimensions: "600x300x40",
          areaM: "0.18",
          areaF: "1.93",
        },
        swatches: [
          "/products/wall-tiles/dry-cladding-forms/hexchain/swatches/swatch-1.jpg",
          "/products/wall-tiles/dry-cladding-forms/hexchain/swatches/swatch-2.jpg",
          "/products/wall-tiles/dry-cladding-forms/hexchain/swatches/swatch-3.jpg",
          "/products/wall-tiles/dry-cladding-forms/hexchain/swatches/swatch-4.jpg",
        ],
        renders: [
          "/products/wall-tiles/dry-cladding-forms/hexchain/renders/render-1.jpg",
          "/products/wall-tiles/dry-cladding-forms/hexchain/renders/render-2.jpg",
          "/products/wall-tiles/dry-cladding-forms/hexchain/renders/render-3.jpg",
          "/products/wall-tiles/dry-cladding-forms/hexchain/renders/render-4.jpg",
        ],
        downloadPdf: "#",
        download3d: "#",
      },
      {
        slug: "hexstar",
        name: "Hexstar",
        image: "/products/wall-tiles/dry-cladding-forms/hexstar/hexstar.png",
        textures: [
          {
            name: "Smooth",
            image: "/products/textures/smooth.png",
          },
        ],
        colors: [
          "brown 4610",
          "brown 4686",
          "brown 4660",
          "Red4180",
          "Maroon",
          "White",
          "Red",
          "Grey",
          "Red 4130",
          "Dholpur",
          "yellow 4910",
          "yellow 4960",
          "yellow 4905",
        ],
        sizeDescription: {
          dimensions: "600x600x40",
          areaM: "0.36",
          areaF: "3.87",
        },
        swatches: [
          "/products/wall-tiles/dry-cladding-forms/hexstar/swatches/swatch-1.jpg",
          "/products/wall-tiles/dry-cladding-forms/hexstar/swatches/swatch-2.jpg",
          "/products/wall-tiles/dry-cladding-forms/hexstar/swatches/swatch-3.jpg",
          "/products/wall-tiles/dry-cladding-forms/hexstar/swatches/swatch-4.jpg",
        ],
        renders: [
          "/products/wall-tiles/dry-cladding-forms/hexstar/renders/render-1.jpg",
          "/products/wall-tiles/dry-cladding-forms/hexstar/renders/render-2.jpg",
          "/products/wall-tiles/dry-cladding-forms/hexstar/renders/render-3.jpg",
          "/products/wall-tiles/dry-cladding-forms/hexstar/renders/render-4.jpg",
        ],
        downloadPdf: "#",
        download3d: "#",
      },
      {
        slug: "mapell",
        name: "Mapell",
        image: "/products/wall-tiles/dry-cladding-forms/mapell/mapell.png",
        textures: [
          {
            name: "Smooth",
            image: "/products/textures/smooth.png",
          },
        ],
        colors: [
          "Brown4610",
          "brown 4686",
          "brown 4660",
          "Red 4180",
          "Grey",
          "Pink",
          "Red 4130",
          "Maroon",
          "yellow 4960",
          "yellow 4910",
          "yellow 4905",
          "yellow 4920",
        ],
        sizeDescription: {
          dimensions: "600x500x40",
          areaM: "0.3",
          areaF: "3.22",
        },
        swatches: [
          "/products/wall-tiles/dry-cladding-forms/mapell/swatches/swatch-1.jpg",
          "/products/wall-tiles/dry-cladding-forms/mapell/swatches/swatch-2.jpg",
          "/products/wall-tiles/dry-cladding-forms/mapell/swatches/swatch-3.jpg",
          "/products/wall-tiles/dry-cladding-forms/mapell/swatches/swatch-4.jpg",
        ],
        renders: [
          "/products/wall-tiles/dry-cladding-forms/mapell/renders/render-1.jpg",
          "/products/wall-tiles/dry-cladding-forms/mapell/renders/render-2.jpg",
          "/products/wall-tiles/dry-cladding-forms/mapell/renders/render-3.jpg",
          "/products/wall-tiles/dry-cladding-forms/mapell/renders/render-4.jpg",
        ],
        downloadPdf: "#",
        download3d: "#",
      },
      {
        slug: "peepal",
        name: "Peepal",
        image: "/products/wall-tiles/dry-cladding-forms/peepal/peepal.png",
        textures: [
          {
            name: "Smooth",
            image: "/products/textures/smooth.png",
          },
        ],
        colors: [
          "Brown4610",
          "brown 4686",
          "brown 4660",
          "Red4180",
          "Grey",
          "Pink",
          "Red 4130",
          "yellow 4920",
          "Dholpur",
          "yellow 4910",
          "yellow 4905",
          "white",
        ],
        sizeDescription: {
          dimensions: "600x500x40",
          areaM: "0.3",
          areaF: "3.22",
        },
        swatches: [
          "/products/wall-tiles/dry-cladding-forms/peepal/swatches/swatch-1.jpg",
          "/products/wall-tiles/dry-cladding-forms/peepal/swatches/swatch-2.jpg",
          "/products/wall-tiles/dry-cladding-forms/peepal/swatches/swatch-3.jpg",
          "/products/wall-tiles/dry-cladding-forms/peepal/swatches/swatch-4.jpg",
        ],
        renders: [
          "/products/wall-tiles/dry-cladding-forms/peepal/renders/render-1.jpg",
          "/products/wall-tiles/dry-cladding-forms/peepal/renders/render-2.jpg",
          "/products/wall-tiles/dry-cladding-forms/peepal/renders/render-3.jpg",
          "/products/wall-tiles/dry-cladding-forms/peepal/renders/render-4.jpg",
        ],
        downloadPdf: "#",
        download3d: "#",
      },
      {
        slug: "pinwheel",
        name: "Pinwheel",
        image: "/products/wall-tiles/dry-cladding-forms/pinwheel/pinwheel.png",
        textures: [
          {
            name: "Smooth",
            image: "/products/textures/smooth.png",
          },
        ],
        colors: [
          "brown 4610",
          "brown 4686",
          "brown 4660",
          "Red4100",
          "Grey",
          "Pink",
          "Maroon",
          "yellow 4905",
          "Dholpur",
          "yellow 4910",
          "yellow 4960",
          "Delhistone",
        ],
        sizeDescription: {
          dimensions: "600x500x40",
          areaM: "0.3",
          areaF: "3.22",
        },
        swatches: [
          "/products/wall-tiles/dry-cladding-forms/pinwheel/swatches/swatch-1.jpg",
          "/products/wall-tiles/dry-cladding-forms/pinwheel/swatches/swatch-2.jpg",
          "/products/wall-tiles/dry-cladding-forms/pinwheel/swatches/swatch-3.jpg",
          "/products/wall-tiles/dry-cladding-forms/pinwheel/swatches/swatch-4.jpg",
        ],
        renders: [
          "/products/wall-tiles/dry-cladding-forms/pinwheel/renders/render-1.jpg",
          "/products/wall-tiles/dry-cladding-forms/pinwheel/renders/render-2.jpg",
          "/products/wall-tiles/dry-cladding-forms/pinwheel/renders/render-3.jpg",
          "/products/wall-tiles/dry-cladding-forms/pinwheel/renders/render-4.jpg",
        ],
        downloadPdf: "#",
        download3d: "#",
      },
      {
        slug: "trihex",
        name: "Trihex",
        image: "/products/wall-tiles/dry-cladding-forms/trihex/trihex.png",
        textures: [
          {
            name: "Smooth",
            image: "/products/textures/smooth.png",
          },
        ],
        colors: [
          "brown 4610",
          "brown 4686",
          "brown 4660",
          "Red4180",
          "Grey",
          "Pink",
          "Red 4100",
          "Red 4130",
          "yellow 4905",
          "yellow 4920",
          "yellow 4910",
          "yellow 4960",
        ],
        sizeDescription: {
          dimensions: "600x400x40",
          areaM: "0.24",
          areaF: "2.58",
        },
        swatches: [
          "/products/wall-tiles/dry-cladding-forms/trihex/swatches/swatch-1.jpg",
          "/products/wall-tiles/dry-cladding-forms/trihex/swatches/swatch-2.jpg",
          "/products/wall-tiles/dry-cladding-forms/trihex/swatches/swatch-3.jpg",
        ],
        renders: [
          "/products/wall-tiles/dry-cladding-forms/trihex/renders/render-1.jpg",
          "/products/wall-tiles/dry-cladding-forms/trihex/renders/render-2.jpg",
          "/products/wall-tiles/dry-cladding-forms/trihex/renders/render-3.jpg",
          "/products/wall-tiles/dry-cladding-forms/trihex/renders/render-4.jpg",
        ],
        downloadPdf: "#",
        download3d: "#",
      },
    ],
  },
  {
    proxy: "wall-tiles",
    slug: "dry-cladding-panels",
    name: "Dry Cladding Panels",
    image: "/products/wall-tiles/dry-cladding-panels/dry-cladding-panels.png",
    subcategories: [
      {
        slug: "autumn",
        name: "Autumn",
        image: "/products/wall-tiles/dry-cladding-panels/autumn/autumn.png",
        textures: [
          {
            name: "Smooth",
            image: "/products/textures/smooth.png",
          },
        ],
        colors: [
          "brown 4610",
          "brown 4686",
          "brown 4660",
          "Red 4180",
          "Maroon",
          "Yellow 4905",
          "Pink",
          "Red 4100",
          "Red4130",
          "Yellow 4920",
          "Yellow 4960",
          "Yellow 4910",
        ],
        sizeDescription: {
          dimensions: "1000x1000x50",
          areaM: "1.0",
          areaF: "10.76",
        },
        swatches: [
          "/products/wall-tiles/dry-cladding-panels/autumn/swatches/swatch-1.jpg",
          "/products/wall-tiles/dry-cladding-panels/autumn/swatches/swatch-2.jpg",
          "/products/wall-tiles/dry-cladding-panels/autumn/swatches/swatch-3.jpg",
          "/products/wall-tiles/dry-cladding-panels/autumn/swatches/swatch-4.jpg",
        ],
        renders: [
          "/products/wall-tiles/dry-cladding-panels/autumn/renders/render-1.jpg",
          "/products/wall-tiles/dry-cladding-panels/autumn/renders/render-2.jpg",
          "/products/wall-tiles/dry-cladding-panels/autumn/renders/render-3.jpg",
          "/products/wall-tiles/dry-cladding-panels/autumn/renders/render-4.jpg",
        ],
        downloadPdf: "#",
        download3d: "#",
      },
      {
        slug: "ledge-cut",
        name: "Ledge Cut",
        image:
          "/products/wall-tiles/dry-cladding-panels/ledge-cut/ledge-cut.png",
        textures: [
          {
            name: "Smooth",
            image: "/products/textures/smooth.png",
          },
        ],
        colors: [
          "Delhi stone",
          "brown 4686",
          "brown 4660",
          "Red 4180",
          "Maroon",
          "Yellow 4905",
          "Pink",
          "Red4100",
          "Red4130",
          "Yellow 4920",
          "Yellow 4960",
          "Yellow 4910",
        ],
        sizeDescription: {
          dimensions: "1000x1000x50",
          areaM: "1.0",
          areaF: "10.76",
        },
        swatches: [
          "/products/wall-tiles/dry-cladding-panels/ledge-cut/swatches/swatch-1.jpg",
          "/products/wall-tiles/dry-cladding-panels/ledge-cut/swatches/swatch-2.jpg",
          "/products/wall-tiles/dry-cladding-panels/ledge-cut/swatches/swatch-3.jpg",
        ],
        renders: [
          "/products/wall-tiles/dry-cladding-panels/ledge-cut/renders/render-1.jpg",
          "/products/wall-tiles/dry-cladding-panels/ledge-cut/renders/render-2.jpg",
          "/products/wall-tiles/dry-cladding-panels/ledge-cut/renders/render-3.jpg",
        ],
        downloadPdf: "#",
        download3d: "#",
      },
      {
        slug: "ledge-stone",
        name: "Ledge Stone",
        image:
          "/products/wall-tiles/dry-cladding-panels/ledge-stone/ledge-stone.png",
        textures: [
          {
            name: "Smooth",
            image: "/products/textures/smooth.png",
          },
        ],
        colors: [
          "brown 4610",
          "brown 4686",
          "brown 4660",
          "Red 4180",
          "Maroon",
          "Yellow 4905",
          "Pink",
          "Red4100",
          "Red4130",
          "Yellow 4920",
          "Yellow 4960",
          "Yellow 4910",
        ],
        sizeDescription: {
          dimensions: "1000x1000x50",
          areaM: "1.0",
          areaF: "10.76",
        },
        swatches: [
          "/products/wall-tiles/dry-cladding-panels/ledge-stone/swatches/swatch-1.jpg",
          "/products/wall-tiles/dry-cladding-panels/ledge-stone/swatches/swatch-2.jpg",
          "/products/wall-tiles/dry-cladding-panels/ledge-stone/swatches/swatch-3.jpg",
        ],
        renders: [
          "/products/wall-tiles/dry-cladding-panels/ledge-stone/renders/render-1.jpg",
          "/products/wall-tiles/dry-cladding-panels/ledge-stone/renders/render-2.jpg",
          "/products/wall-tiles/dry-cladding-panels/ledge-stone/renders/render-3.jpg",
        ],
        downloadPdf: "#",
        download3d: "#",
      },
      {
        slug: "p-tesella",
        name: "P Tesella",
        image:
          "/products/wall-tiles/dry-cladding-panels/p-tesella/p-tesella.png",
        textures: [
          {
            name: "Smooth",
            image: "/products/textures/smooth.png",
          },
        ],
        colors: [
          "brown 4610",
          "brown 4686",
          "brown 4660",
          "Red 4180",
          "Maroon",
          "Yellow 4905",
          "Pink",
          "Red 4100",
          "Red4130",
          "Yellow 4920",
          "Yellow 4960",
          "Yellow 4910",
        ],
        sizeDescription: {
          dimensions: "1000x1000x50",
          areaM: "1.0",
          areaF: "10.76",
        },
        swatches: [
          "/products/wall-tiles/dry-cladding-panels/p-tesella/swatches/swatch-1.jpg",
          "/products/wall-tiles/dry-cladding-panels/p-tesella/swatches/swatch-2.jpg",
          "/products/wall-tiles/dry-cladding-panels/p-tesella/swatches/swatch-3.jpg",
          "/products/wall-tiles/dry-cladding-panels/p-tesella/swatches/swatch-4.jpg",
        ],
        renders: [
          "/products/wall-tiles/dry-cladding-panels/p-tesella/renders/render-1.jpg",
          "/products/wall-tiles/dry-cladding-panels/p-tesella/renders/render-2.jpg",
          "/products/wall-tiles/dry-cladding-panels/p-tesella/renders/render-3.jpg",
          "/products/wall-tiles/dry-cladding-panels/p-tesella/renders/render-4.jpg",
        ],
        downloadPdf: "#",
        download3d: "#",
      },
      {
        slug: "scutes",
        name: "Scutes",
        image: "/products/wall-tiles/dry-cladding-panels/scutes/scutes.png",
        textures: [
          {
            name: "Smooth",
            image: "/products/textures/smooth.png",
          },
        ],
        colors: [
          "brown 4610",
          "brown 4686",
          "brown 4660",
          "Red 4180",
          "Maroon",
          "Yellow 4905",
          "Pink",
          "Red 4100",
          "Red4130",
          "Yellow 4920",
          "Yellow 4960",
          "Yellow 4910",
        ],
        sizeDescription: {
          dimensions: "1000x1000x50",
          areaM: "1.0",
          areaF: "10.76",
        },
        swatches: [
          "/products/wall-tiles/dry-cladding-panels/scutes/swatches/swatch-1.jpg",
          "/products/wall-tiles/dry-cladding-panels/scutes/swatches/swatch-2.jpg",
          "/products/wall-tiles/dry-cladding-panels/scutes/swatches/swatch-3.jpg",
        ],
        renders: [
          "/products/wall-tiles/dry-cladding-panels/scutes/renders/render-1.jpg",
          "/products/wall-tiles/dry-cladding-panels/scutes/renders/render-2.jpg",
          "/products/wall-tiles/dry-cladding-panels/scutes/renders/render-3.jpg",
          "/products/wall-tiles/dry-cladding-panels/scutes/renders/render-4.jpg",
        ],
        downloadPdf: "#",
        download3d: "#",
      },
      {
        slug: "s-tesella",
        name: "S Tesella",
        image:
          "/products/wall-tiles/dry-cladding-panels/s-tesella/s-tesella.png",
        textures: [
          {
            name: "Smooth",
            image: "/products/textures/smooth.png",
          },
        ],
        colors: [
          "brown 4610",
          "brown 4686",
          "brown 4660",
          "Red 4180",
          "Maroon",
          "Yellow 4905",
          "Pink",
          "Delhi stone",
          "Red4130",
          "Yellow 4920",
          "Yellow 4960",
          "Yellow 4910",
        ],
        sizeDescription: {
          dimensions: "1000x1000x50",
          areaM: "1.0",
          areaF: "10.76",
        },
        swatches: [
          "/products/wall-tiles/dry-cladding-panels/s-tesella/swatches/swatch-1.jpg",
          "/products/wall-tiles/dry-cladding-panels/s-tesella/swatches/swatch-2.jpg",
          "/products/wall-tiles/dry-cladding-panels/s-tesella/swatches/swatch-3.jpg",
          "/products/wall-tiles/dry-cladding-panels/s-tesella/swatches/swatch-4.jpg",
        ],
        renders: [
          "/products/wall-tiles/dry-cladding-panels/s-tesella/renders/render-1.jpg",
          "/products/wall-tiles/dry-cladding-panels/s-tesella/renders/render-2.jpg",
          "/products/wall-tiles/dry-cladding-panels/s-tesella/renders/render-3.jpg",
          "/products/wall-tiles/dry-cladding-panels/s-tesella/renders/render-4.jpg",
        ],
        downloadPdf: "#",
        download3d: "#",
      },
      {
        slug: "tyde",
        name: "Tyde",
        image: "/products/wall-tiles/dry-cladding-panels/tyde/tyde.png",
        textures: [
          {
            name: "Smooth",
            image: "/products/textures/smooth.png",
          },
        ],
        colors: [
          "brown 4610",
          "brown 4686",
          "brown 4660",
          "Red 4180",
          "Maroon",
          "Yellow 4905",
          "Pink",
          "Delhi stone",
          "Red4130",
          "Yellow 4920",
          "Yellow 4960",
          "Yellow 4910",
        ],
        sizeDescription: {
          dimensions: "1000x1000x50",
          areaM: "1.0",
          areaF: "10.76",
        },
        swatches: [
          "/products/wall-tiles/dry-cladding-panels/tyde/swatches/swatch-1.jpg",
          "/products/wall-tiles/dry-cladding-panels/tyde/swatches/swatch-2.jpg",
          "/products/wall-tiles/dry-cladding-panels/tyde/swatches/swatch-3.jpg",
          "/products/wall-tiles/dry-cladding-panels/tyde/swatches/swatch-4.jpg",
        ],
        renders: [
          "/products/wall-tiles/dry-cladding-panels/tyde/renders/render-1.jpg",
          "/products/wall-tiles/dry-cladding-panels/tyde/renders/render-2.jpg",
          "/products/wall-tiles/dry-cladding-panels/tyde/renders/render-3.jpg",
        ],
        downloadPdf: "#",
        download3d: "#",
      },
      {
        slug: "v-flute",
        name: "V Flute",
        image: "/products/wall-tiles/dry-cladding-panels/v-flute/v-flute.png",
        textures: [
          {
            name: "Smooth",
            image: "/products/textures/smooth.png",
          },
        ],
        colors: [
          "brown 4610",
          "brown 4686",
          "brown 4660",
          "Red 4180",
          "Maroon",
          "Yellow 4905",
          "Pink",
          "Red4100",
          "Red4130",
          "Yellow 4920",
          "Yellow 4960",
          "Yellow 4910",
        ],
        sizeDescription: {
          dimensions: "1000x1000x50",
          areaM: "1.0",
          areaF: "10.76",
        },
        swatches: [
          "/products/wall-tiles/dry-cladding-panels/v-flute/swatches/swatch-1.jpg",
          "/products/wall-tiles/dry-cladding-panels/v-flute/swatches/swatch-2.jpg",
          "/products/wall-tiles/dry-cladding-panels/v-flute/swatches/swatch-3.jpg",
          "/products/wall-tiles/dry-cladding-panels/v-flute/swatches/swatch-4.jpg",
        ],
        renders: [
          "/products/wall-tiles/dry-cladding-panels/v-flute/renders/render-1.jpg",
          "/products/wall-tiles/dry-cladding-panels/v-flute/renders/render-2.jpg",
          "/products/wall-tiles/dry-cladding-panels/v-flute/renders/render-3.jpg",
          "/products/wall-tiles/dry-cladding-panels/v-flute/renders/render-4.jpg",
          "/products/wall-tiles/dry-cladding-panels/v-flute/renders/render-5.jpg",
        ],
        downloadPdf: "#",
        download3d: "#",
      },
    ],
  },
  {
    proxy: "wall-tiles",
    slug: "wet-cladding-panel",
    name: "Wet Cladding Panel",
    image: "/products/wall-tiles/wet-cladding-panel/wet-cladding-panel.png",
    subcategories: [
      {
        slug: "arcade",
        name: "Arcade",
        image: "/products/wall-tiles/wet-cladding-panel/arcade/arcade.png",
        textures: [
          {
            name: "Smooth",
            image: "/products/textures/smooth.png",
          },
        ],
        colors: [
          "brown 4610",
          "brown 4686",
          "brown 4660",
          "Red 4180",
          "Maroon",
          "Yellow 4905",
          "Dholpur",
          "white",
          "Yellow 4920",
          "Yellow 4960",
          "Yellow 4910",
        ],
        sizeDescription: {
          dimensions: "300x900x15",
          areaM: "0.27",
          areaF: "2.91",
        },
        swatches: [
          "/products/wall-tiles/wet-cladding-panel/arcade/swatches/swatch-1.jpg",
          "/products/wall-tiles/wet-cladding-panel/arcade/swatches/swatch-2.jpg",
          "/products/wall-tiles/wet-cladding-panel/arcade/swatches/swatch-3.jpg",
        ],
        renders: [
          "/products/wall-tiles/wet-cladding-panel/arcade/renders/render-1.jpg",
          "/products/wall-tiles/wet-cladding-panel/arcade/renders/render-2.jpg",
          "/products/wall-tiles/wet-cladding-panel/arcade/renders/render-3.jpg",
        ],
        downloadPdf: "#",
        download3d: "#",
      },
      {
        slug: "ridges",
        name: "ridges",
        image: "/products/wall-tiles/wet-cladding-panel/ridges/ridges.png",
        textures: [
          {
            name: "Coarse",
            image: "/products/textures/Coarse.png",
          },
        ],
        colors: [
          "brown 4610",
          "brown 4686",
          "brown 4660",
          "delhistone",
          "Maroon",
          "Yellow 4905",
          "grey",
          "white",
          "red 4130",
          "Yellow 4920",
          "Yellow 4960",
          "Yellow 4910",
        ],
        sizeDescription: {
          dimensions: "600x900x22",
          areaM: "0.54",
          areaF: "5.81",
        },
        swatches: [
          "/products/wall-tiles/wet-cladding-panel/ridges/swatches/swatch-1.jpg",
          "/products/wall-tiles/wet-cladding-panel/ridges/swatches/swatch-2.jpg",
          "/products/wall-tiles/wet-cladding-panel/ridges/swatches/swatch-3.jpg",
          "/products/wall-tiles/wet-cladding-panel/ridges/swatches/swatch-4.jpg",
        ],
        renders: [
          "/products/wall-tiles/wet-cladding-panel/ridges/renders/render-1.jpg",
          "/products/wall-tiles/wet-cladding-panel/ridges/renders/render-2.jpg",
          "/products/wall-tiles/wet-cladding-panel/ridges/renders/render-3.jpg",
        ],
        downloadPdf: "#",
        download3d: "#",
      },
    ],
  },
];

export default WallTilePages;
